ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('add_to_cart/<int:pk>',views.add_to_cart,name='add_to_cart'),
    path('cart_view/',views.cart_view,name='cart_view'),
    path('cart_decrement/<int:d>', views.cart_decrement, name='cart_decrement'),
    path('cart_trash/<int:p>',views.cart_trash,name='cart_trash'),
    path('place_order',views.orderform,name='place_order'),
    path('status/<u>',views.payment_status,name='payment_sataus'),
    path('order_view',views.order_view,name='order_view')

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
    path('search_product/',views.search_product,name='search_product'),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path

from shop import views

app_name='shop'
urlpatterns = [
    path('',views.home,name='home'),
    path('category',views.category,name='category'),
    path('product/<int:i>',views.product,name='product'),
    path('productdetails/<int:i>',views.productdetails,name='productdetails'),
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout')

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

from django.http import HttpResponse

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    data_added=models.DateTimeField(auto_now_add=True)

    # def subtotal(self):
    #     return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

#
class Order_table(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    phone=models.CharField(max_length=30)
    address=models.TextField()
    pin=models.CharField(max_length=30)
    ordered_date=models.DateTimeField(auto_now_add=True)
    order_id=models.CharField(max_length=100,blank=True)
    payment_status=models.CharField(default="pending",max_length=30)
    delivery_status=models.CharField(default="pending",max_length=30)


    def __str__(self):
        return self.user.username



class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.CharField(max_length=100)
    order_id=models.CharField(max_length=100,blank=True)
    razorpay_payment_id=models.CharField(max_length=100,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import render,redirect

from shop.models import Product
from cart.models import Cart
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from cart.models import Payment
from .models import Order_table


#
from django.views.decorators.csrf import csrf_exempt

import razorpay

# Create your views here.
@login_required
def add_to_cart(request,pk):
    p=Product.objects.get(id=pk)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if(p.stock):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            p.save()

    # return HttpResponse('product is added to cart')
    return redirect('cart:cart_view')


@login_required
def cart_view(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total+=i.quantity*i.product.price

    return render(request,'cart.html',{'cart':cart,'total':total})

@login_required
def cart_decrement(request,d):
    p = Product.objects.get(id=d)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if(cart.quantity>1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock +=1
            p.save()
    except:
        pass

    return redirect('cart:cart_view')


@login_required
def cart_trash(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        q=cart.delete()
        p.stock +=cart.quantity
        p.save()

    except:
        pass
    return redirect('cart:cart_view')

@login_required

def orderform(request):
    if(request.method=='POST'):
        ph=request.POST.get('p')
        a=request.POST.get('a')
        n=request.POST.get('n')
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total=total+(i.quantity*i.product.price)     #Total amount
        total=int(total*100)

        #create Razorpay client using our API credentials
        client=razorpay.Client(auth=('rzp_test_WwAeIbYfM7kzyI','FPK6OKnPtRRvAm0lRNyu6qVt'))

        #create order in Razorpay
        response_payment=client.order.create(dict(amount=total,currency='INR'))
#
#

        print(response_payment)

        order_id=response_payment['id']
        order_status=response_payment['status']
        if order_status == "created":
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()

            for i in c:
                o=Order_table.objects.create(user=u,product=i.product,address=a,phone=ph,pin=n,no_of_items=i.quantity,order_id=order_id)
                o.save()
        response_payment['name']=u.username

        return render(request,'payment.html',{'payment':response_payment})
#
    return render(request,'place_order.html')

@csrf_exempt
def payment_status(request,u):
    print(request.user.is_authenticated) #false
    if not request.user.is_authenticated:
        user = User.objects.get(username=u)
        login(request,user)
        print(user.is_authenticated) #true

    if(request.method=="POST"):          #Razorpay response after completion of payment
        response=request.POST
        # print(u)
        print(response)
        #to check the authenticity of razorpay signature
        param_dict = {
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }
        client = razorpay.Client(auth=('rzp_test_WwAeIbYfM7kzyI','FPK6OKnPtRRvAm0lRNyu6qVt'))
        try:
            status=client.utility.verify_payment_signature(param_dict)# to check the authenticity of razorpay signature
            print(status)

#After sucessful payment

            #retrive a payment record with particular order_id
#         #create payment table enter details
            ord = Payment.objects.get(order_id=response['razorpay_order_id'])
            ord.razorpay_payment_id = response['razorpay_payment_id']#edit payment id response['razorpay_payment_id']
            ord.paid = True# edit paid to true
            ord.save()


            c=Cart.objects.filter(user=user)
            print(user.username)
              #filterthe order_table details for particular user with order_id=response['razorpay_order_id']

            o=Order_table.objects.filter(user=user,order_id=response['razorpay_order_id'])
            print(o)
            for i in o:
                i.payment_status="paid"#edit payment_status="paid
                i.save()
            c.delete() #to delete cart items
            print(status)
            return render(request,'payment_status.html',{'status':True})
        except:
            return render(request,'payment_status.html',{'status':False})

    return render(request,'payment_status.html')

@login_required

def order_view(request):
    u=request.user
    customer=Order_table.objects.filter(user=u,payment_status="paid")


    return render(request,'order_view.html',{'customer':customer,'u':u.username})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
        <i class="fa-solid fa-cart-shopping" style="font-size:50px;color:red;"></i>
        <a class="navbar-brand" href="#">E-SHOP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}

                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">HOME</a>
                    </li>

                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       ALL CATEGORIES
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          {% for  i in links %}
                        <li><a class="dropdown-item" href="{% url 'shop:product' i.id %}">{{i.name}}</a></li>
                        {% endfor %}

                      </ul>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-plus" style="font-size:200%;color:#f518d0"></i> <sup class="fw-bold" style="color:blue;font-size:20px;">{{count}}</sup></a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href=" {% url 'cart:order_view' %}">YOUR ORDER</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">LOGOUT</a>
                    </li>
            </ul>
                {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">REGISTER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">LOGIN</a>
                    </li>
                 </ul>
                {% endif %}
                <form class="d-flex" method="post"  action="{% url 'search:search_product' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
        </div>
    </div>
</nav>


<br>
<br>
{% block content%}
{% endblock %}
<footer>
<hr>
    <div class="container " style="margin-bottom:70px" >
    <p style="font-size:20px; color:red;">Copyright @2024 Myshop.All Rights Reserved</p>
   </div>

</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">
	<div class="row">
<center><h2>Shopping Cart</h2></center>
		<div class="col-7">
			<table class="table table-bordered">
				<tr><th colspan="6">cart items</th>
				</tr>
				{% for i in cart %}
				<tr>
					<td><img src="{{i.product.image.url}}" width="150px" height="150px"></td>
					<td>{{i.product.name}}</td>
					<td><b>Product ID:{{i.product.id}}</b><br></td>
					<td><b>Quantity:{{i.quantity}}</b><br>
					  <b>Unit Price:{{i.quantity}}*{{i.product.price}}</b></td>
					<td>Subtotal:{{i.subtotal}}</td>

					<td>
						  {% if i.product.stock > 0 %}
						  <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus"></i></a>
						<br><a href="{% url 'cart:cart_decrement' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a>

						<br><a href="{% url 'cart:cart_trash' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
						{% else %}
						<br><a href="{% url 'cart:cart_decrement' i.product.id %}"><i class="fa-solid fa-minus" style="color:black"></i></a>
						<br><a href="{% url 'cart:cart_trash' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
						{% endif %}
					</td>
				</tr>
				{% endfor %}
			</table>
		</div>
		     <div class="col-4">
				 <table class="table table-borderder">
					 <tr><th colspan="4">checkout</th></tr>
					 <tr>
						 <td class="fw-bold">Total Amount:{{total}}</td>
					 </tr>
				 </table>
				 <center><a href="{% url 'cart:place_order' %}" class="btn btn-primary" style="..">Place order</a><br><br>
				 <a href="{% url 'shop:category' %}" class="btn btn-warning">Continue Shopping</a></center>
			 </div>
	</div>
</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
<img src="{% static 'image/ebay.jpg' %}">
   <center><h2>EBAY</h2></center>
  <p class="fs-5 fw-bolder fst-italic text-decoration-undereline">performance and strategic initiatives. eBay Inc (eBay) is an e-commerce marketplace that connects buyers and sellers. The company through its platform offers antiques, art, baby products, books, auto parts and accessories, clothing, shoes, lifestyle accessories, collectibles, office equipment, craft, and electronics.</p>
  <br>

  <div class="row mt-5 mt-5">
   {% for i in item %}

        <div class="col-sm-3">
             <div class="card border border-1 border-primary" style="width: 18rem ;">
                <img src="{{i.image.url}}" style="height:300px;width:100%"  alt="...">
                   <div class="card-body">
                        <h4 class="card-text">{{i.name}}</h4>
                           <a href="{% url 'shop:product' i.id %}" class="btn btn-primary">SHOP NOW</a>
                   </div>
             </div>

      </div>

      {% endfor %}

</div>
</div>
{% endblock %}

ecommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>HOME PAGE....</h2>
<img src ="{% static 'image/home.png' %}" style="width:100%; height:500px;">

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>LOGIN</title>
{% endblock %}

{% block content %}

<center>
   <h2>LOGIN  HERE.......</h2>
<form class="container" method="post" >

  {% csrf_token %}

  <div class="mb-3">
  <label class="form-label">Usernane</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter Username">
</div>
  <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter Password">
</div>
<div >

    <button type="submit" class="btn btn-primary">SUBMIT</button>
</div>
</form>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</center>
{% endblock %}

ecommerce/templates/order_view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row" style="margin-top:80px;">
      <h3 class="text-center fw-bold">Name of Customer:{{u}}</h3>
      {% for i in customer %}


    <div class="col-5 mx-auto">
        <img src="{{i.product.image.url }}" height="150px" width="50%" >
    </div>

    <div class="col-6 " style="align-item:center;">
       <hr class="mx-auto">
        <h5>{{i.product.name}}</h5>
        <h5>{{i.product.price}}</h5>
        <h5>{{i.address}}</h5>
        <h5>{{i.ordered_date}}</h5>


    </div>
 {% endfor %}
  </div>
</div>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2>Payment</h2>
    <div class="container bg-dark mt-3 " style ="height:200px;width:50%;padding-top:100px">
<form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" method="POST">
    {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_WwAeIbYfM7kzyI"
    data-amount="{{payment.amount}}"
    data-currency="{{payment.currency}}"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="E-Shop"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://static.vecteezy.com/system/resources/previews/003/275/721/large_2x/shopping-bag-store-logo-online-shopping-logo-design-free-vector.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="you@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
 </center>

{% endblock %}

ecommerce/templates/payment_status.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}


{% if status == True %}
    <div class="container">

    <i class="fa fa-check-circle"  aria-hidden="true" style="font-size:80px;color:green;margin-left:370px"></i>
        <h3 style="color:green;margin-left:370px;">Thank you.Your payment was sucessful</h3> </div>
{% else %}
<h3 style='color:green;margin-left:130px;'>Your payment is failed.Try Again</h3>
{% endif %}

{% endblock %}

ecommerce/templates/place_order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2>Enter Details</h2>

<div class="container bg-success">
<form method="POST">
      {% csrf_token %}



      <div class="mb-3">
          <label class="form-label">Phone No</label>
          <input type="text" class="form-control" name="p"  >
      </div>

      <div class="mb-3">
          <label class="form-label">Delivery Address</label>
          <input type="text" class="form-control" name="a"  >
      </div>
      <div class="mb-3">
          <label class="form-label">Pin</label>
          <input type="text" class="form-control" name="n"  >
      </div>


      <button type="submit" class="form-control">Submit</button></form>

</div>
</center>

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
<center><img src="{{c.image.url}}" height="300px" width="50%">
  <h2>{{c.name}}</h2></center>
  <p class="fs-5 fw-bolder fst-italic text-decoration-undereline">{{c.desc}}</p>
  <br>

  <div class="row mt-5 mt-5">
   {% for i in p %}

        <div class="col-sm-3">
             <div class="card border border-1 border-primary" style="width: 18rem ;">
                <a href="#"> <img src="{{i.image.url}}" style="height:300px;width:100%"  alt="..."></a>
                   <div class="card-body">
                        <h4 class="card-text">{{i.name}}</h4>
                          <p class="card-text">{{i.price}}</p>
                          <p class="card-text">Available:{{i.stock}}</p>
                           <a href="{% url 'shop:productdetails' i.id %}" class="btn btn-primary">Details</a>
                   </div>
             </div>

      </div>

      {% endfor %}

</div>
</div>
{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<div class="container-fluid">
  <div class="row mt-3 mb-3">
    <div class="col">
      <img src="{{t.image.url}}" height="300px" width="50%">
    </div>
    <div class="col">
      <h1>{{t.name}}</h1>
      <h4>{{t.desc}}</h4>
      <h2>{{t.price}}</h2>
       <h2>{{t.stock}}</h2>
      {% if user.is_superuser == True %}
          {% if t.stock > 0 %}
              <h3 class="text-sucess">Product in Stock</h3>
               <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
          {% else %}
                <h3 class="text-danger">Out of Stock</h3>
                 <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
          {% endif %}
      {% else %}
          {% if t.stock > 0 %}
                 <a href="{% url 'cart:add_to_cart' t.id %}"  class="btn-1">Add To Cart</a>
          {% else %}
                 <h3 class="text-danger">Out Of Stock</h3>
          {% endif %}
      {% endif %}

          <h3>Product Details <i style="" class="fa fa-indent"></i></h3>



    </div>
  </div>
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  <title>REGISTER</title>
{% endblock %}


{% block content %}
 <h2>Register Here.....</h2>
<center>
<form method="post" >

  {% csrf_token %}

  <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter username">
</div>
  <div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter password">
</div>
   <div class="mb-3">
  <label class="form-label"> Confirm Password</label>
  <input type="password" class="form-control" name="cp"  placeholder="Enter confirm password">
</div>
  <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name= "e"  >
</div>

   <div class="mb-3">
  <label class="form-label">First_Name</label>
  <input type="text" class="form-control" name="f"  placeholder="Enter first name">
</div>
   <div class="mb-3">
  <label class="form-label">Last_Name</label>
  <input type="text" class="form-control" name="l"  placeholder="Enter last name">
</div>

  <div class="mb-3">
    <input type="submit" class="form-control">
  </div>
</center>
</form>
{% endblock %}

ecommerce/templates/searchproduct.html
{% extends 'base.html'%}
{% load static %}



{% block content %}

<h2 class="mt-3 mb-3">Search result of {{query}}</h2>


<div class="container mt-3">
  {% if p %}
  <div class="row">
    {% for i in p %}
      <div class="col-4 mt-4">
        <div class="card" style="width: 18rem;">
          <a href="{% url 'shop:productdetails' i.id %}">
            <img src="{{i.image.url}}" class="card-img-top" height="250px" width="150px" alt="..." ></a>
          <div class="card-body">
            <center>
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.price}}</p>
                <p class="card-text">Available:{{i.stock}}</p>
              <a href="#" class="btn btn-primary">Shop Now</a>
            </center>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    <div class="col-md-12" style="">
      <h4 class="fn-bold text-center">No Search Found..</h4>
    </div>
      {% endif %}
  </div>
</div>


{% endblock %}